//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log_Recorder.DA.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class User:INotifyPropertyChanged
    {
        private string _userName;
        private Nullable<byte> _userRoleId;
        public int UserId { get; set; }
        public string UserName 
        {
            get { return _userName; }
            set
            {
                _userName = value;
                if (PropertyChanged != null)
                    PropertyChanged(this, new PropertyChangedEventArgs("UserName"));
            }
        }
        public string Password { get; set; }
        public Nullable<byte> UserRoleId 
        {
            get { return _userRoleId; }
            set
            {
                _userRoleId = value;
                if (PropertyChanged != null)
                    PropertyChanged(this, new PropertyChangedEventArgs("UserRoleId"));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}
